spring.application.name=Students
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/Students
spring.datasource.username=postgres
spring.datasource.password=India@1947
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
