spring.application.name=billing-service
server.port=9091
spring.datasource.url=jdbc:postgresql://localhost:5432/billing_db
spring.datasource.username=postgres
spring.datasource.password=India@1947
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=billing-group
spring.kafka.consumer.auto-offset-reset=earliest